services:
  backend_spring:
    container_name: backend_spring
    build:
      context: ./web-service/yacontest-helper/.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=db_password
    depends_on:
      - database

  database:
    image: postgres
    container_name: database

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=db_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s

    ports:
    - "5432:5432"