spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: db_password
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      enabled: true

  jpa:
    hibernate.ddl-auto: update
    properties.hibernate:
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

  feign:
    client:
      config:
        yaContestClient:
          connectTimeout: 5000
          readTimeout: 5000
          loggerLevel: basic


configs:
  base-contest-url: https://api.contest.yandex.net/api/public/v2

  get-submission-list:
    page-size: 128
    url: https://api.contest.yandex.net/api/public/v2/contests/%s/submissions

security:
  jwt-secret: ${SECRET_KEY_JWT}
  auth-validity-period-seconds: ${AUTH_TOKEN_VALIDITY_PERIOD_SEC}
  refresh-validity-period-seconds: ${REFRESH_TOKEN_VALIDITY_PERIOD_SEC}